### ISSUE TITLE
Mapping to unknown type smalldatetime

### ISSUE THREAD

**Issue by ericung** [Avanade/NTangle#18]
How do I handle mapping smalldatetime to a current .NET type for the CodeGen part of the code? I think smalldatetime in SqlServer to .NET is outdated based on my current research. This is the error that pops up when running AppName.CodeGen for nTangle.

'Database data type 'smalldatetime' does not have corresponding .NET type mapping defined.'

**Comment by chullybun** [comment]
Hi @ericung - change has been made to `DbEx` package (version `v1.0.14`) to add `smalldatetime` (see [repo](https://github.com/Avanade/DbEx/blob/3c930d1acdd8321d37076593b90d9483e895bfe8/src/DbEx/Schema/DbTypeMapper.cs#L55)). Add the latest `DbEx` package dependency to your project which should override `NTangle` referenced version to resolve your issue. Let me know how you get on?

**Comment by wborowiecki** [comment]
Hi @chullybun, when nuget with this version will be available? Right now the latest version of nTanble is 1.0.5 that uses DbEx 1.0.11.

**Comment by chullybun** [comment]
hi @wborowiecki, updated and published new package; see `v1.0.6`. apologies for delay, turns out there was another issue in `DbEx` that needed to be resolved - should be good to go now :-)
