### ISSUE TITLE
AddAzureServiceBusClient callback with ServiceBusClientOptions would be nice

### ISSUE THREAD

**Issue by wborowiecki** [Avanade/NTangle#21]
In ServiceCollectionExtensions it would be nice to have an additional extension that accepts Action<ServiceBusClientOptions> and use it in ConfigureOptions extension for IAzureClientBuilder something like: cb.AddServiceBusClient(sbcs).ConfigureOptions(q)

**Comment by chullybun** [comment]
Hi @wborowiecki , this was related to _CoreEx_ functionality; this change has been included since `CoreEx v1.0.9`; use as follows:

``` csharp
.AddAzureServiceBusClient(connectionName: nameof(HrSettings.ServiceBusConnection), configure: (o, sp) => o.RetryOptions.MaxRetries = 3)
```
