### ISSUE TITLE
Add possibility to run as windows service, not just as console app 

### ISSUE THREAD

**Issue by wborowiecki** [Avanade/NTangle#24]
It would be nice to add the possibility to run nTangle as a Windows service or Linux daemon, not just as a console app.
In that way, we could deploy it on a VM, it could then restart automatically after VM reboot. 
Also, it would not require having an active session to run it.

**Comment by chullybun** [comment]
The console application is the default created for the `Publisher` when using the `Template` to generate the solution/projects. This was chosen as this is the easiest to create and supports simple testing; plus, acts as an appropriate demonstration of how to use the `*HostedServices` (via `AddGeneratedCdcHostedServices`), etc.

There are many host options, windows service being one of them, or alternatively an Azure Function, etc. Therefore, it is up to the _developer_ to change the `Publisher` into the appropriate host for their respective scenario.
